name: Update Contributors
on:
  schedule:
    - cron: '0 0 * * *' # Daily update
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch contributors
        run: |
          curl -s https://api.github.com/repos/${{ github.repository }}/contributors > public/contributors.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/contributors.json
          git commit -m "Update contributors" || echo "No changes"
          git push